name: Update Publications

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday
  workflow_dispatch: # Allows manual triggering

jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install scholarly pyyaml

      - name: Fetch and update publications
        run: python fetch_publications.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _publications/*.md _data/publications.yml
          git commit -m "Auto-update publications from Google Scholar"
          git push
